config: './configs/config.yaml'
image_path: './data/train/image/'
mask_path: './data/train/mask/'
val_image: './data/test/MDvsFA/image/'
val_mask: './data/test/MDvsFA/mask/'
save_path: './outputs'
box_save_path: './data/train/train_box_gt.csv'
pos_mode: 'cosin'
iou_thres: 0.6
conf_thres: 0.2
topk: 5
nel: 4
stride: 16
loss_mode: null
seg_posw: 3
obj_posw: 10
max_det_num: 5
hidden_dim: 512
d_lr: 0.01
s_lr: 0.001
batch_size: 16
epochs: 10
rpn_pretrained: null
expand: 8
fast: false